config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                              Controller#Action
#                     root GET    /                                        visitors#index
#         new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
#            user_password POST   /users/password(.:format)                devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)            devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
#                          PATCH  /users/password(.:format)                devise/passwords#update
#                          PUT    /users/password(.:format)                devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PATCH  /users(.:format)                         devise/registrations#update
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#                    users GET    /users(.:format)                         users#index
#                          POST   /users(.:format)                         users#create
#                 new_user GET    /users/new(.:format)                     users#new
#                edit_user GET    /users/:id/edit(.:format)                users#edit
#                     user GET    /users/:id(.:format)                     users#show
#                          PATCH  /users/:id(.:format)                     users#update
#                          PUT    /users/:id(.:format)                     users#update
#                          DELETE /users/:id(.:format)                     users#destroy
#             inscriptions GET    /inscriptions(.:format)                  inscriptions#index
#                          POST   /inscriptions(.:format)                  inscriptions#create
#          new_inscription GET    /inscriptions/new(.:format)              inscriptions#new
#         edit_inscription GET    /inscriptions/:id/edit(.:format)         inscriptions#edit
#              inscription GET    /inscriptions/:id(.:format)              inscriptions#show
#                          PATCH  /inscriptions/:id(.:format)              inscriptions#update
#                          PUT    /inscriptions/:id(.:format)              inscriptions#update
#                          DELETE /inscriptions/:id(.:format)              inscriptions#destroy
#              suggestions GET    /suggestions(.:format)                   suggestions#index
#                          POST   /suggestions(.:format)                   suggestions#create
#           new_suggestion GET    /suggestions/new(.:format)               suggestions#new
#          edit_suggestion GET    /suggestions/:id/edit(.:format)          suggestions#edit
#               suggestion GET    /suggestions/:id(.:format)               suggestions#show
#                          PATCH  /suggestions/:id(.:format)               suggestions#update
#                          PUT    /suggestions/:id(.:format)               suggestions#update
#                          DELETE /suggestions/:id(.:format)               suggestions#destroy
#              invitations GET    /invitations(.:format)                   invitations#index
#                          POST   /invitations(.:format)                   invitations#create
#           new_invitation GET    /invitations/new(.:format)               invitations#new
#          edit_invitation GET    /invitations/:id/edit(.:format)          invitations#edit
#               invitation GET    /invitations/:id(.:format)               invitations#show
#                          PATCH  /invitations/:id(.:format)               invitations#update
#                          PUT    /invitations/:id(.:format)               invitations#update
#                          DELETE /invitations/:id(.:format)               invitations#destroy
#             portal_index GET    /portal/index(.:format)                  portal#index
#                          GET    /backend/invitations/:action(.:format)   backend/invitations#:action
#                          GET    /backend/registrations/:action(.:format) backend/registrations#:action
#                          GET    /backend/suggestions/:action(.:format)   backend/suggestion_processing#:action
#                  backend GET    /backend(.:format)                       backend/backend#index
#                     page GET    /pages/*id                               high_voltage/pages#show
#

Rails.application.routes.draw do

  get 'backend_tools/guest_emails'

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    match '/users/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end

  ## WARNING - needs to be commented out when creating a DATABASE from scratch
  ## BOOTSTRAPPING / SETUP
  ActiveAdmin.routes(self)

  root to: 'visitors#index'

  resources :users
  get '/users/:id/reset_password', to: 'users#reset_password'
  resources :inscriptions
  resources :suggested_participants
  resources :previous_participants
  resources :registrations, controller: 'inscriptions', type: 'Registration', model_name: 'Registration'

  match '/invitations/new_couple', to: 'invitations#new_couple', via: 'get'
  match '/invitations/create_couple', to: 'invitations#create_couple', via: 'post'
  get "/invitations/send_invite_to_user/:id", to: "invitations#send_invite_to_user"
  get "/invitation/accept/:id/:invitation_token", to: "invitations#accept"
  get "/invitation/convert/:id", to: "invitations#convert"

  resources :invitations do
    member do
      get 'reset_invitation_key'
      delete 'expire'
    end
  end

  get '/rsvp/:action', :controller => 'rsvp'


  scope :backend do
    resource :suggested_participants
    resource :invitations
    get '/statistics/:action', :controller => 'backend_statistics'
    get '/tools/:action', :controller => 'backend_tools'
  end
  match "/backend/suggestions/by_guests", to: 'backend/suggestion_processing#convert_to_invitation', via: 'post'
  match "/backend/suggestions/previous_participants", to: 'backend/suggestion_processing#convert_pp_to_invitation', via: 'post'
  match '/backend/invitations/button_action', :controller => 'backend/invitations', via: 'post'
  match '/backend/registrations/button_action', :controller => 'backend/registrations', via: 'post'

  match '/backend/registration/:id/show', :controller => 'backend/registrations', :action => 'show', via: 'get'
  match '/backend/registration/:id/edit', :controller => 'backend/registrations', :action => 'edit', via: 'get'
  match '/backend/registration/:id/update', :controller => 'backend/registrations', :action => 'admin_update', via: 'post'


  match '/portal', to: 'portal#index', via: 'get'
  get 'portal/index'
  get 'portal/guestlist'
  get 'portal/map'
  get 'portal/suggest'
  match '/portal/update_dietary', controller: 'portal', action: 'update_dietary', via: 'patch'

  get '/backend/invitations/:action', :controller => 'backend/invitations'
  get '/backend/registrations/:action', :controller => 'backend/registrations'
  get '/backend/suggestions/:action', :controller => 'backend/suggestion_processing'


  get '/backend', to: 'backend/backend#dashboard'
  get '/backend/stats', to: 'backend/backend#stats'
  get '/backend/stats2', to: 'backend/backend#stats2'
  get '/backend/signup_stats', to: 'backend/backend#signup_stats'
  get '/backend/signup_vs_accepted', to: 'backend/backend#signup_vs_accepted'
  get '/backend/guestlist', to: 'backend/backend#guestlist'
  get '/backend/aushang_guestlist', to: 'backend/backend#aushang_guestlist'
  get '/backend/csv', to: 'backend/backend#csv'
  get '/backend/fb_pics', to: 'backend/backend#fb_pics'
  get '/backend/view_portal_for_user_select', to: 'backend/backend#view_portal_for_user_select'
  get "/backend/user_portal_check/", to: "backend/backend#view_portal_for_user"

end

app/models/invitation.rb
# == Schema Information
#
# Table name: inscriptions
#
#  id                       :integer          not null, primary key
#  type                     :string
#  first_name               :string
#  last_name                :string
#  email                    :string
#  gender                   :string
#  role                     :string
#  birthday                 :date
#  street                   :string
#  city                     :string
#  zip                      :string
#  country                  :string
#  facebook                 :string
#  gmaps                    :boolean
#  latitude                 :float
#  longitude                :float
#  distance                 :decimal(, )
#  zodiac_sign_id           :integer
#  dietary_class            :integer          default(0)
#  dietary_incompatibility  :integer          default(0)
#  permission_to_store_data :boolean          default(TRUE)
#  message                  :text
#  telephone                :string
#  partner_email            :string
#  partner_first_name       :string
#  partner_last_name        :string
#  user_id                  :integer
#  suggestion_id            :integer
#  partner_id               :integer
#  created_at               :datetime
#  updated_at               :datetime
#  state                    :string           default("start")
#  processing_list          :string           default("start")
#  email_state              :string           default("start")
#

class Invitation < Inscription
  include InvitationStateable
  delegate :email, to: :user

end

app/controllers/backend/invitations_controller.rb
class Backend::InvitationsController < ApplicationController

  before_filter :authenticate_user!
  layout 'backend'


  def list
    @tasks_grid = initialize_grid(Invitation,
                                  :include => [:user],
                                  :order   => 'id')

    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  def processing
    case params[:filter]
      when 'no_reply'
        @where_clause = "Invitation.where(:state => 'paid')"
      when 'declined'
        @where_clause = "Invitation.where(:state => 'declined')"
      when 'sent'
        @where_clause = "Invitation.sent"
      when 'not_sent'
        @where_clause = "Invitation.not_sent"
      when 'open'
        @where_clause = "Invitation.open"
      when 'no_email'
        @where_clause = "Invitation.joins(:user).where(:users => {:invitation_sent_at => nil})"
      when 'expired'
        @where_clause = "Invitation.expired"
      else
        @where_clause = 'Invitation'
    end

    @tasks_grid = initialize_grid(eval(@where_clause),
                                  :include         => [:user],
                                  :order           => 'id',
                                  :order_direction => 'desc',
                                  :per_page        => 100)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  def messages
    @tasks_grid = initialize_grid(Invitation.where("message <> ''"),
                                  :include         => [:user],
                                  :order           => 'id',
                                  :order_direction => 'desc',
                                  :per_page        => 100)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  def create_from_previous_participant
    @invitation = Invitation.new_with_previous_participant(PreviousParticipant.find(params[:id]), current_user)
    #@invitation.inviter_id=current_user.id

    User.invite!(:email => @invitation.email, :name => @invitation.name) do |u|
      u.skip_invitation = true
      u.facebook_id     = @invitation.facebook
      u.save
      @invitation.user=u
      #@invitation.save!
    end
    # => the record will be created, but the invitation email will not be sent

    if @invitation.save
      redirect_to edit_invitation_path(@invitation)
    end
  end

  def button_action
    if !params[:grid][:selected]
      flash[:error] = "Please select a row before pressing the buttons."
    elsif params[:reset_keys] == ""
      reset_keys
    elsif params[:send_invitation] == ""
      send_invitation
    elsif params[:decline_invitation] == ""
      decline_invitation
    elsif params[:delete_invitation] == ""
      delete_invitation
    elsif params[:expire_invitation] == ""
      expire_invitation
    else
    end
    redirect_to :action => :processing
  end

  def reset_keys
    flash[:notice] = "Resetting keys for "
    params[:grid][:selected].each do |id|
      res, operation = Invitation::ResetInvitationKey.run(invitation: Invitation.find(id)) do |op|
        flash[:notice] += "#{op.model.email} "
        # => the record will be created, but the invitation email will not be sent
      end
    end
  end

  def send_invitation
    flash[:notice] = "Sending invitation emails for #{params[:grid][:selected]}"
    params[:grid][:selected].each do |id|
      res, operation = Invitation::SendEmail.run(user: Invitation.find(id).user) do |op|
        flash[:notice] += "#{op.model.email} "
      end
    end
  end

  def decline_invitation
    flash[:notice] = "Manually declining invitation for #{params[:grid][:selected]}"
    params[:grid][:selected].each do |id|
      res, operation = Invitation::Decline.run(user: Invitation.find(id).user) do |op|
        flash[:notice] += "#{op.model.email} "
      end
    end
  end

  def delete_invitation
    flash[:error] = "Deleting invitation for #{params[:grid][:selected]}"
    params[:grid][:selected].each do |id|
      Invitation.find(id).delete
    end
  end

  def expire_invitation
    flash[:error] = "Expiring invitation for #{params[:grid][:selected]}"
    params[:grid][:selected].each do |id|
      res, operation = Invitation::Expire.run(model: Invitation.find(id)) do |op|
        flash[:error] += "#{op.model.email} "
      end
    end

  end


end

app/views/invitations/_form.html.haml
.card
  .header
    = content_for(:heading)? yield(:heading) : "Invitation"
  .content
    = simple_form_for(@form) do |f|
      = f.error_notification
      - if (defined? @invitation.inviter and !@invitation.inviter.nil?)
        %h4
          invited by User ##{@invitation.inviter.id.to_s + "/" + @invitation.inviter.email}
      .form-actions
        = f.button :submit
      .form-inputs
        .row
          .col-lg-3
            = f.input :first_name
          .col-lg-3
            = f.input :last_name
          .col-lg-3
            = f.fields_for :user do |u|
              = u.input :email
        .row
          .col-lg-3
            = f.input :facebook, placeholder: 'userid'
        .row
          .col-lg-2
            = f.input :gender, as: :radio_buttons, collection: gender_options
          .col-lg-2
            = f.input :role, as: :radio_buttons, collection: roles
        .row
          .col-lg-3
            = f.input :city
          .col-lg-3
            = f.input :country
        .row
          .col-lg-3
            = f.input :message

app/views/invitations/_form_couple.html.haml
.row
  .span4.well
    %h3 She
    = simple_form_for @invitation1, :url => url_for(:action => 'create_couple', :controller => 'invitations'), :method => 'post' do |f|
      = f.error_notification
      .form-inputs
        = f.input :first_name
        = f.input :last_name
        = f.input :email, placeholder: 'user@domain.com'
        = f.input :role, as: :radio_buttons, collection: roles, input_html: { value: '1' }
        = f.input :city
        = f.input :country
        = f.input :facebook, placeholder: 'userid', hint: 'note: we can pull a profile picture from fb, if we like'
  .span4.well
    %h3 He
    = simple_fields_for (:invitation2) do |fa|
      .form-inputs
        = fa.input :first_name
        = fa.input :last_name
        = fa.input :email, placeholder: 'user@domain.com'
        = fa.input :role, as: :radio_buttons, collection: roles
        = fa.input :city
        = fa.input :country
        = fa.input :facebook, placeholder: 'userid', hint: 'note: we can pull a profile picture from fb, if we like', required: false
%div
  = f.input :message, as: :text, placeholder: 'Do you want to add a personalized message?'
.form-actions.span9
  = f.button :submit

app/views/invitations/accept.html.haml
Hello world

app/views/invitations/create_couple.html.haml
= decorate_raw_object(params)

app/views/invitations/edit.html.haml
- content_for :heading do
 Edit Invitation
= render 'form'

app/views/invitations/index.html.haml
%h1 List of current invitations
%table.table.table-striped.table-condensed
  %tr
    %th
    %th ID
    %th Name
    %th Email
    %th Role
    %th Added
    %th ACTIONS
  - @invitations.each do |invitation|
    - picture_url = invitation.facebook.blank? ? '' : 'http://graph.facebook.com/' + invitation.facebook + '/picture'
    - invited_user = invitation.user_id.nil? ? nil : invitation.user
    %tr
      %td
        %img{:src => picture_url}/
      %td= invited_user.nil? ? "" : invited_user.id
      %td= invitation.name
      %td= invitation.email
      %td= invitation.role
      %td= invitation.created_at.stamp("2013-05-20")
      %td= invitation.user_id.nil? ? "" : invitation.user.invitation_token
      %td= link_to 'Show', invitation
      %td= link_to 'Edit', edit_invitation_path(invitation)
      %td= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Invitation', new_invitation_path

app/views/invitations/new.html.haml
- content_for :heading do
 New Invitation
= render 'form'

app/views/invitations/new_couple.html.haml
.page-header
  %h1 New couple invitation
  = link_to 'Back to overview', '/backend/invitations/processing'
= render 'form_couple'

app/views/invitations/send_invite_to_user.html.haml
Sending invite to #{@user.name}.

app/views/invitations/show.html.haml
.col-lg-12
  .card
    .header
      Invitation
      .btn.btn-success
        #{link_to 'Edit', edit_invitation_path(@invitation)}
      .btn.btn-info
        #{link_to 'Back', '/backend/invitations/processing'}
      .btn.btn-error
        =link_to "<span class='glyphicon glyphicon-retweet'></span>".html_safe, "/invitations/#{@invitation.id}/reset_invitation_key"
    .content
      %table.table
        %tr
          %td
            %b
              Name
          %td
            = @invitation.name
        %tr
          %td
            %b
              Email
          %td
            = @invitation.email
        %tr
          %td
            %b
              Dancer
          %td
            = @invitation.role.titlecase
            ,
            = @invitation.gender
        %tr
          %td
            %b
              Address
          %td
            = @invitation.address
        %tr
          %td
            %b
              Facebook
          %td
            = @invitation.facebook
        %tr
          %td
            %b
              Message
          %td
            = @invitation.message
        %tr
          %td
            %b
              Emails
          %td
            %table.table
              %thead
                %th Email
                %th Sent
                %th Campaign Monitor Message ID
                %th Status
                %th Opens
                %th Clicks
              - @invitation.email_logs.sort_by{ |x| -x.id}.each do |log|
                %tr
                  %td=log.message
                  %td=log.created_at
                  %td=log.message_ID
                  %td=log.status
                  - email_stats = CreateSend::Transactional::Timeline.new(@auth).details(log.message_ID)
                  %td=email_stats.TotalOpens
                  %td=email_stats.TotalClicks

      .col-lg-6
        %h4 User
        = (ap @invitation.user, :html => true, :plain => true).html_safe
      .col-lg-6
        %h4 Invitation
        = (ap @invitation, :html => true, :plain => true).html_safe