config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                              Controller#Action
#                     root GET    /                                        visitors#index
#         new_user_session GET    /users/sign_in(.:format)                 devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                 devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                devise/sessions#destroy
#            user_password POST   /users/password(.:format)                devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)            devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
#                          PATCH  /users/password(.:format)                devise/passwords#update
#                          PUT    /users/password(.:format)                devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                  devise/registrations#cancel
#        user_registration POST   /users(.:format)                         devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                 devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                    devise/registrations#edit
#                          PATCH  /users(.:format)                         devise/registrations#update
#                          PUT    /users(.:format)                         devise/registrations#update
#                          DELETE /users(.:format)                         devise/registrations#destroy
#                    users GET    /users(.:format)                         users#index
#                          POST   /users(.:format)                         users#create
#                 new_user GET    /users/new(.:format)                     users#new
#                edit_user GET    /users/:id/edit(.:format)                users#edit
#                     user GET    /users/:id(.:format)                     users#show
#                          PATCH  /users/:id(.:format)                     users#update
#                          PUT    /users/:id(.:format)                     users#update
#                          DELETE /users/:id(.:format)                     users#destroy
#             inscriptions GET    /inscriptions(.:format)                  inscriptions#index
#                          POST   /inscriptions(.:format)                  inscriptions#create
#          new_inscription GET    /inscriptions/new(.:format)              inscriptions#new
#         edit_inscription GET    /inscriptions/:id/edit(.:format)         inscriptions#edit
#              inscription GET    /inscriptions/:id(.:format)              inscriptions#show
#                          PATCH  /inscriptions/:id(.:format)              inscriptions#update
#                          PUT    /inscriptions/:id(.:format)              inscriptions#update
#                          DELETE /inscriptions/:id(.:format)              inscriptions#destroy
#              suggestions GET    /suggestions(.:format)                   suggestions#index
#                          POST   /suggestions(.:format)                   suggestions#create
#           new_suggestion GET    /suggestions/new(.:format)               suggestions#new
#          edit_suggestion GET    /suggestions/:id/edit(.:format)          suggestions#edit
#               suggestion GET    /suggestions/:id(.:format)               suggestions#show
#                          PATCH  /suggestions/:id(.:format)               suggestions#update
#                          PUT    /suggestions/:id(.:format)               suggestions#update
#                          DELETE /suggestions/:id(.:format)               suggestions#destroy
#              invitations GET    /invitations(.:format)                   invitations#index
#                          POST   /invitations(.:format)                   invitations#create
#           new_invitation GET    /invitations/new(.:format)               invitations#new
#          edit_invitation GET    /invitations/:id/edit(.:format)          invitations#edit
#               invitation GET    /invitations/:id(.:format)               invitations#show
#                          PATCH  /invitations/:id(.:format)               invitations#update
#                          PUT    /invitations/:id(.:format)               invitations#update
#                          DELETE /invitations/:id(.:format)               invitations#destroy
#             portal_index GET    /portal/index(.:format)                  portal#index
#                          GET    /backend/invitations/:action(.:format)   backend/invitations#:action
#                          GET    /backend/registrations/:action(.:format) backend/registrations#:action
#                          GET    /backend/suggestions/:action(.:format)   backend/suggestion_processing#:action
#                  backend GET    /backend(.:format)                       backend/backend#index
#                     page GET    /pages/*id                               high_voltage/pages#show
#

Rails.application.routes.draw do

  get 'backend_tools/guest_emails'

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    match '/users/sign_out', to: 'devise/sessions#destroy', via: 'delete'
  end

  ## WARNING - needs to be commented out when creating a DATABASE from scratch
  ## BOOTSTRAPPING / SETUP
  ActiveAdmin.routes(self)

  root to: 'visitors#index'

  resources :users
  get '/users/:id/reset_password', to: 'users#reset_password'
  resources :inscriptions
  resources :suggested_participants
  resources :previous_participants
  resources :registrations, controller: 'inscriptions', type: 'Registration', model_name: 'Registration'

  match '/invitations/new_couple', to: 'invitations#new_couple', via: 'get'
  match '/invitations/create_couple', to: 'invitations#create_couple', via: 'post'
  get "/invitations/send_invite_to_user/:id", to: "invitations#send_invite_to_user"
  get "/invitation/accept/:id/:invitation_token", to: "invitations#accept"
  get "/invitation/convert/:id", to: "invitations#convert"

  resources :invitations do
    member do
      get 'reset_invitation_key'
      delete 'expire'
    end
  end

  get '/rsvp/:action', :controller => 'rsvp'


  scope :backend do
    resource :suggested_participants
    resource :invitations
    get '/statistics/:action', :controller => 'backend_statistics'
    get '/tools/:action', :controller => 'backend_tools'
  end
  match "/backend/suggestions/by_guests", to: 'backend/suggestion_processing#convert_to_invitation', via: 'post'
  match "/backend/suggestions/previous_participants", to: 'backend/suggestion_processing#convert_pp_to_invitation', via: 'post'
  match '/backend/invitations/button_action', :controller => 'backend/invitations', via: 'post'
  match '/backend/registrations/button_action', :controller => 'backend/registrations', via: 'post'

  match '/backend/registration/:id/show', :controller => 'backend/registrations', :action => 'show', via: 'get'
  match '/backend/registration/:id/edit', :controller => 'backend/registrations', :action => 'edit', via: 'get'
  match '/backend/registration/:id/update', :controller => 'backend/registrations', :action => 'admin_update', via: 'post'


  match '/portal', to: 'portal#index', via: 'get'
  get 'portal/index'
  get 'portal/guestlist'
  get 'portal/map'
  get 'portal/suggest'
  match '/portal/update_dietary', controller: 'portal', action: 'update_dietary', via: 'patch'

  get '/backend/invitations/:action', :controller => 'backend/invitations'
  get '/backend/registrations/:action', :controller => 'backend/registrations'
  get '/backend/suggestions/:action', :controller => 'backend/suggestion_processing'


  get '/backend', to: 'backend/backend#dashboard'
  get '/backend/stats', to: 'backend/backend#stats'
  get '/backend/stats2', to: 'backend/backend#stats2'
  get '/backend/signup_stats', to: 'backend/backend#signup_stats'
  get '/backend/signup_vs_accepted', to: 'backend/backend#signup_vs_accepted'
  get '/backend/guestlist', to: 'backend/backend#guestlist'
  get '/backend/aushang_guestlist', to: 'backend/backend#aushang_guestlist'
  get '/backend/csv', to: 'backend/backend#csv'
  get '/backend/fb_pics', to: 'backend/backend#fb_pics'
  get '/backend/view_portal_for_user_select', to: 'backend/backend#view_portal_for_user_select'
  get "/backend/user_portal_check/", to: "backend/backend#view_portal_for_user"

end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  before_filter :logged_in
  layout 'portal'

  def index
    @user = current_user
    @reg  = @user.registration
    Rails.logger.info "#{@user} in portal"

    if @user.admin
      redirect_to backend_path
    elsif @reg and (@reg.state == "start")
      redirect_to edit_registration_path @reg
    elsif @reg
      @suggestions = @reg.suggestions

      # if we have signed up with a partner, make that a suggestion, if it's not yet a suggestion
      if @reg.partner
        # if the partner has signed up yet, then there is no need to convert that partner to another suggestion
      elsif (@suggestions.size == 0) and !@reg.partner_email.blank? and !@reg.partner_first_name.blank? and !@reg.partner_last_name.blank?
        SuggestedParticipant::SuggestPartner.(model: @reg)
        @suggestions = @reg.suggestions
      end

    else
      # Invitation was not converted to Registration yet
      redirect_to '/rsvp/index'
    end
  end

  def map

  end

  def guestlist
    @registrations = Registration.all

    @user = current_user

    @markers = MapWorker.generate_markers

  end

  def suggest
    @user                  = current_user
    @reg                   = @user.inscription
    @suggestions           = @reg.suggestions

    # suggestion rules
    @remaining_suggestions = Settings.features.suggestions.number - @suggestions.count

  end

  def update_dietary
    @user                                                = current_user
    @reg                                                 = @user.registration
    params[:registration][:dietary_incompatibility_list] = params[:registration][:dietary_incompatibility_list].join(',')
    if @reg.update_attributes(reg_params)
      redirect_to portal_path :notice => "Successfully updated dietary options."
    else
      redirect_to portal_path :error => "Did not update dietary options."
    end
  end


  private

  def reg_params
    params.require(:registration).permit(:dietary_incompatibility_list,
                                         :dietary_class_list)
  end

end

app/helpers/portal_helper.rb
module PortalHelper
end

app/views/portal/_expalantion_suggestion_short.haml
%div{class: 'explanation add_suggestion_info'}
  %p
    This is the place where you can suggest people to be invited, once you are 'IN'
    Please note, you can only suggest three people, so chose wisely :)

app/views/portal/_explanation_suggestions.haml
%div{class: 'explanation add_suggestion'}
  %p
    This is the place where you can suggest people to be invited.
  %p
    Please note, you can only suggest up to 3 people (2 leaders, 1 follower), so chose wisely :)
  - if @suggestions.count > 0
    %p
      You already suggested #{@suggestions.count} people.
      %table.table.table-condensed.table-striped
        %thead
          %th #
          %th Name
          %th Email
          %th Role
          %th Status
        - @suggestions.each do |s|
          %tr
            - i ||= 1
            %td= "#{i}."
            %td= s.name rescue "error"
            %td= s.email
            %td= ApplicationDecorator.format_role s.role
            %td= status_of_registration_with_email(s.email)
  - else
    %p
      You have not suggested anyone yet.
  %p
    Since leaders are always in short supply, we will process your suggestions in this order:
    %span.label.label-info
      Leader
    %span.label.label-warning
      Follower
    %span.label.label-info
      Leader

app/views/portal/_guest_navbar.haml
%li
  %a{href: Settings.marathon.website}
    =Settings.marathon.name
%li= link_to 'Logout', destroy_user_session_path, :method=>'delete'
%li{class: 'home'}
  %a{href: portal_index_path }
    Portal
- if current_user.is_guest?
  %li{class: 'guestlist'}
    %a{href: portal_guestlist_path }
      Guestlist
- if Settings.features.suggestions.enabled and (current_user.registration.suggestions.count >0)
  %li{class:  'suggestions' }
    %a{href: portal_suggest_path}
      #{current_user.registration.suggestions.count} Suggestions

app/views/portal/_guestlist_map_script.haml
:javascript
  L.mapbox.accessToken = 'pk.eyJ1IjoiZGFuaWVsayIsImEiOiJjaW80b3M1dG4wMDNkdmtrcHN0cHBzNHgwIn0.jsXVIuBfGFwnxD4NrOPLHw';
  var map = L.mapbox.map('map', 'mapbox.streets').setView([#{Settings.venue.gps.lat}, #{Settings.venue.gps.lon}], 4);
  #{@markers}

app/views/portal/_index_map_script.haml
:javascript
  L.mapbox.accessToken =
    'pk.eyJ1IjoiZGFuaWVsayIsImEiOiJjaW80b3M1dG4wMDNkdmtrcHN0cHBzNHgwIn0.jsXVIuBfGFwnxD4NrOPLHw';
  var geocoder = L.mapbox.geocoder('mapbox.places');
  var map = L.mapbox.map('map', 'mapbox.streets').on('ready', function() {
                  new L.Control.MiniMap(L.mapbox.tileLayer('mapbox.streets'))
      .addTo(map);
      });
  geocoder.query('#{Settings.venue.name}', showMap);

  function showMap(err, data) {
      // The geocoder can return an area, like a city, or a
      // point, like an address. Here we handle both cases,
      // by fitting the map bounds to an area or zooming to a point.
      if (data.lbounds) {
          map.fitBounds(data.lbounds);
      } else if (data.latlng) {
          map.setView([data.latlng[0], data.latlng[1]], 14);
      }
  }

  L.marker([49.407498, 8.1895652], {
        icon: L.mapbox.marker.icon({
            'marker-size': 'large',
            'marker-color': '#fa0'
        })
    }).addTo(map);

app/views/portal/_map_infowindow.html.haml
%p
  = reg.first_name.titleize

app/views/portal/guestlist.html.haml
- content_for :title do
  = Settings.marathon.name + " - Guest List"
.container
  .row
    %h1 Confirmed Guests
    %p
      Geolocation is jittered to protect privacy of guests.
      #{MapWorker.print_no_geocode} marks guests without a pin on the map
    %div{:style => "width: 100%;"}
      #map{:style => "width: 100%; height: 600px;"}
    - %w(followers leaders both).each do |role|
      .col-xs-12.col-md-6.col-lg-3
        %h3=role.titlecase
        %table.table.table-striped
          %th
          %th Name
          %th City
          - collection = eval("@registrations.#{role}")
          - collection.sort_alphabetical_by { |e| e[:first_name].capitalize }.each do |reg|
            %tr
              %td= ZodiacDecorator.format_zodiac_sign_for_inscription reg
              %td= reg.first_name.titleize
              %td
                = reg.city.titleize
                = reg.geocoded? ? '' : MapWorker.print_no_geocode
= render :partial => 'guestlist_map_script'

app/views/portal/index.html.haml
- content_for :title do
  = Settings.marathon.name + " - Guest Portal for #{current_user.inscription.name}"
.container
  .row
    .col-lg-12
      %h1
        Hallo #{@reg.first_name.titleize}, good to see you again!
      - if Settings.marathon.registration.refund
        %p
          %span.label.label-warning='Reminder'
          While cancellations are possible at any time,
          %b
            refunds are only possible
          before
          = (Settings.marathon.registration.norefund_after).stamp('March 3rd 2015') + "."
      - else
        %p
          %span.label.label-warning='Reminder'
          While cancellations are possible at any time,
          %b
            there are no refunds! If you need to cancel, please contact us in time,
            and we might be able to work something out!
      %div.card{:style => "width: 100%;"}
        #map{:style => "width: 100%; height: 200px;"}
        = render partial: 'index_map_script'

  .row
    - if Settings.marathon.event.start.future?
      .col-xs-12.col-lg-6
        .card
          .header
            %h3
              Your registration status
          .content
            %div{style: 'display: inline-block;'}
              = concept('registration/status', @reg)
      - if Settings.features.suggestions.enabled
        - if @reg.is_guest? or @reg.accepted?
          .col-xs-12.col-lg-6
            .card
              .header
                %h3
                  Suggest friends
                  %a{href: portal_suggest_path, class: 'btn btn-success add_suggestion'} Click here
              .content
                = render :partial => 'explanation_suggestions'
        - else
          .col-xs-12.col-lg-6
            .card
              .header
                %h3
                  Suggest friends
              .content
                = render :partial => 'expalantion_suggestion_short'
        .col-xs-12.col-lg-6
          .card
            .header
              %h3
                Your data
            .content
              %div{style: 'display: inline-block;'}
                = concept('registration/personal_data', @reg)
              %div
                %h4
                  Please check your dietary options
                = render 'inscriptions/form_dietary'
          .card
            .header
              %h3
                Your partner's data
            .content
              %div{style: 'display: inline-block;'}
                = concept('registration/partner', @reg)

app/views/portal/suggest.haml
- content_for :title do
  = Settings.marathon.name + " - Guest Portal Suggestions"
.container
  .row
    .col-lg-12
      %h2 Your Suggestions
      %h3 Please suggest up to #{Settings.features.suggestions.number} friends for a merry party!
      %p You may suggest up to two leaders and one follower.
      %p
        We will maintain a balanced and diverse guestlist, and we will take your suggestions into account.
        However, we cannot and will not guarantee that we can invite everyone who was suggested!
      - if @reg
        %p
          You have #{@remaining_suggestions} suggestions left.
          - if @remaining_suggestions > 0
            = link_to 'Suggest Friend', new_suggested_participant_path , :class => "btn btn-success"
            %br/
      %table.table
        %tr
          %th
          %th Name
          %th Email
          %th Role
          %th Added
          %th Your Comment
          %th Status
          %th ACTIONS
          - i ||= 1
        - @suggestions.each do |suggestion|
          %tr
            %td= "#{i}."
            %td= suggestion.name
            %td= suggestion.email
            %td= ApplicationDecorator.format_role suggestion.role
            %td
              = time_ago_in_words suggestion.created_at
              ago
            %td= suggestion.message
            %td= status_of_registration_with_email suggestion.email
            %td= link_to 'Edit', edit_suggested_participant_path(suggestion)
            - i += 1